superbuild_add_project(g2o
  DEPENDS eigen

  CMAKE_ARGS
  -DG2O_BUILD_EXAMPLES=OFF
  -DG2O_BUILD_APPS=OFF
  -Dg2o_RUNTIME_OUTPUT_DIRECTORY=bin
  -Dg2o_LIBRARY_OUTPUT_DIRECTORY=lib
  -DCMAKE_INSTALL_RPATH=<INSTALL_DIR>/lib
)
