# launch lidarview CI, see https://docs.gitlab.com/ee/ci/multi_project_pipelines.html
launch_lidarview_CI:
  variables:
    TRIGGER_MODULE_SHA: $CI_COMMIT_SHA
    TRIGGER_MODULE_PATH: LVCore
  only:
    - master
    - merge_requests
    - tags
  trigger:
    project: lidarview/lidarview
    branch: master
    strategy: depend
